from django.urls import path
from .views import signup, admin_dashboard, notes, gk, pradesh, model_sets, quizzes, templates_page, blog, gallery, contact, services, toggle_bookmark, job_board, job_post, admin_forbidden, pradesh_detail
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic.base import RedirectView
from . import firebase_views
from . import firebase_admin_views

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('accounts/signup/', signup, name='accounts_signup'),

    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='accounts_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('dashboard/', admin_dashboard, name='admin_dashboard'),
    path('notes/', notes, name='notes'),
    path('gk/', gk, name='gk'),
    path('gk/<str:pk>/', views.gk_detail, name='gk_detail'),
    path('pradesh/', pradesh, name='pradesh'),
    path('pradesh/<str:pk>/', pradesh_detail, name='pradesh_detail'),
    path('model-sets/', model_sets, name='model_sets'),
    path('current-event/', views.current_event, name='current_event'),
    path('current-event/<str:pk>/', views.current_event_detail, name='current_event_detail'),
    path('templates/', templates_page, name='templates_page'),
    path('blog/', blog, name='blog'),
    path('blog/<str:pk>/', views.blog_detail, name='blog_detail'),
    path('gallery/', gallery, name='gallery'),
    path('contact/', contact, name='contact'),
    path('services/', services, name='services'),
    path('bookmark/<str:model_name>/<str:object_id>/', toggle_bookmark, name='toggle_bookmark'),
    path('job-board/', job_board, name='job_board'),
    path('job-post/', job_post, name='job_post'),
    path('admin/forbidden/', admin_forbidden, name='admin_forbidden'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    # Password reset URLs temporarily disabled
    # path('accounts/password-reset/', views.DjongoPasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    # path('password-reset/', views.DjongoPasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    # path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('manage-notes/', views.manage_notes, name='manage_notes'),
    path('delete-note/<str:note_id>/', views.delete_note, name='delete_note'),
    path('manage-current-event/', views.manage_current_event, name='manage_current_event'),
    path('edit-current-event/<str:event_id>/', views.edit_current_event, name='edit_current_event'),
    path('delete-current-event/<str:event_id>/', views.delete_current_event, name='delete_current_event'),
    path('current-event/<str:pk>/', views.current_event_detail, name='current_event_detail'),
    path('manage-blog/', views.manage_blog, name='manage_blog'),
    path('edit-blog/<str:article_id>/', views.edit_blog, name='edit_blog'),
    path('delete-blog/<str:article_id>/', views.delete_blog, name='delete_blog'),
    path('manage-templates/', views.manage_templates, name='manage_templates'),
    path('edit-template/<str:template_id>/', views.edit_template, name='edit_template'),
    path('delete-template/<str:template_id>/', views.delete_template, name='delete_template'),
    path('manage-gk/', views.manage_gk, name='manage_gk'),
    path('edit-gk/<str:gk_id>/', views.edit_gk, name='edit_gk'),
    path('delete-gk/<str:gk_id>/', views.delete_gk, name='delete_gk'),
    path('manage-pradesh/', views.manage_pradesh, name='manage_pradesh'),
    path('manage-model-sets/', views.manage_model_sets, name='manage_model_sets'),
    path('manage-gallery/', views.manage_gallery, name='manage_gallery'),
    path('edit-gallery/<str:image_id>/', views.edit_gallery, name='edit_gallery'),
    path('delete-gallery/<str:image_id>/', views.delete_gallery, name='delete_gallery'),
    path('manage-jobs/', views.manage_jobs, name='manage_jobs'),
    path('edit-job/<str:job_id>/', views.edit_job, name='edit_job'),
    path('delete-job/<str:job_id>/', views.delete_job, name='delete_job'),
    path('edit-pradesh/<str:pradesh_id>/', views.edit_pradesh, name='edit_pradesh'),
    path('delete-pradesh/<str:pradesh_id>/', views.delete_pradesh, name='delete_pradesh'),
    path('accounts/edit-profile/', RedirectView.as_view(url='/edit-profile/', permanent=True)),
    path('objectives/', views.objectives, name='objectives'),
    path('subjectives/', views.subjectives, name='subjectives'),
    path('subjectives/<str:subject_id>/', views.subjective_chapters, name='subjective_chapters'),
    path('subjectives/<str:subject_id>/<str:chapter_id>/', views.subjective_qas, name='subjective_qas'),
    path('manage-objectives/', views.manage_objectives, name='manage_objectives'),
    path('manage-subjectives/', views.manage_subjectives, name='manage_subjectives'),
    path('manage-subjective-chapters/<str:subject_id>/', views.manage_subjective_chapters, name='manage_subjective_chapters'),
    path('manage-subjective-qas/<str:chapter_id>/', views.manage_subjective_qas, name='manage_subjective_qas'),
    
    # New Objective URLs
    path('objectives/subject/<str:subject_id>/', views.objective_subject_detail, name='objective_subject_detail'),
    path('objectives/set/<str:set_id>/', views.objective_set_detail, name='objective_set_detail'),
    
    # Admin Objective URLs
    path('manage-objective-subjects/', views.manage_objective_subjects, name='manage_objective_subjects'),
    path('edit-objective-subject/<str:subject_id>/', views.edit_objective_subject, name='edit_objective_subject'),
    path('delete-objective-subject/<str:subject_id>/', views.delete_objective_subject, name='delete_objective_subject'),
    path('manage-objective-sets/<str:subject_id>/', views.manage_objective_sets, name='manage_objective_sets'),
    path('edit-objective-set/<str:set_id>/', views.edit_objective_set, name='edit_objective_set'),
    path('delete-objective-set/<str:set_id>/', views.delete_objective_set, name='delete_objective_set'),
    path('manage-objective-mcqs/<str:set_id>/', views.manage_objective_mcqs, name='manage_objective_mcqs'),
    path('edit-objective-mcq/<str:mcq_id>/', views.edit_objective_mcq, name='edit_objective_mcq'),
    path('delete-objective-mcq/<str:mcq_id>/', views.delete_objective_mcq, name='delete_objective_mcq'),
    path('edit-subjective-chapter/<str:chapter_id>/', views.edit_subjective_chapter, name='edit_subjective_chapter'),
    path('delete-subjective-chapter/<str:chapter_id>/', views.delete_subjective_chapter, name='delete_subjective_chapter'),
    path('edit-subjective-qa/<str:qa_id>/', views.edit_subjective_qa, name='edit_subjective_qa'),
    path('delete-subjective-qa/<str:qa_id>/', views.delete_subjective_qa, name='delete_subjective_qa'),
    path('edit-subjective-subject/<str:subject_id>/', views.edit_subjective_subject, name='edit_subjective_subject'),
    path('delete-subjective-subject/<str:subject_id>/', views.delete_subjective_subject, name='delete_subjective_subject'),
    path('manage-categories/', views.manage_categories, name='manage_categories'),
    path('manage-categories/edit/<str:category_id>/', views.edit_category, name='edit_category'),
    path('manage-categories/delete/<str:category_id>/', views.delete_category, name='delete_category'),
    path('admin/manage-model-sets/', views.manage_model_sets, name='manage_model_sets'),
    path('admin/edit-model-set/<str:set_id>/', views.edit_model_set, name='edit_model_set'),
    path('admin/delete-model-set/<str:set_id>/', views.delete_model_set, name='delete_model_set'),
    
    # Firebase Upload URLs (New - without modifying existing)
    path('firebase/upload-note/<str:note_id>/', firebase_views.upload_note_to_firebase, name='upload_note_to_firebase'),
    path('firebase/upload-gk/<str:gk_id>/', firebase_views.upload_gk_to_firebase, name='upload_gk_to_firebase'),
    path('firebase/upload-article/<str:article_id>/', firebase_views.upload_article_to_firebase, name='upload_article_to_firebase'),
    path('firebase/upload-template/<str:template_id>/', firebase_views.upload_template_to_firebase, name='upload_template_to_firebase'),
    path('firebase/upload-gallery/<str:gallery_id>/', firebase_views.upload_gallery_to_firebase, name='upload_gallery_to_firebase'),
    path('firebase/upload-event/<str:event_id>/', firebase_views.upload_event_to_firebase, name='upload_event_to_firebase'),
    
    # Firebase Admin Upload URLs (New - for direct Firebase uploads)
    path('admin/firebase/upload-note/', firebase_admin_views.firebase_upload_note, name='firebase_upload_note'),
    path('admin/firebase/upload-gk/', firebase_admin_views.firebase_upload_gk, name='firebase_upload_gk'),
    path('admin/firebase/upload-article/', firebase_admin_views.firebase_upload_article, name='firebase_upload_article'),
    path('admin/firebase/upload-template/', firebase_admin_views.firebase_upload_template, name='firebase_upload_template'),
    path('admin/firebase/upload-gallery/', firebase_admin_views.firebase_upload_gallery, name='firebase_upload_gallery'),
    path('admin/firebase/upload-event/', firebase_admin_views.firebase_upload_event, name='firebase_upload_event'),
    path('admin/firebase/upload-pradesh/', firebase_admin_views.firebase_upload_pradesh, name='firebase_upload_pradesh'),
    path('admin/firebase/upload-modelset/', firebase_admin_views.firebase_upload_modelset, name='firebase_upload_modelset'),
    path('admin/firebase/upload-job/', firebase_admin_views.firebase_upload_job, name='firebase_upload_job'),
    path('admin/firebase/upload-objective/', firebase_admin_views.firebase_upload_objective, name='firebase_upload_objective'),
    path('admin/firebase/upload-subjective/', firebase_admin_views.firebase_upload_subjective, name='firebase_upload_subjective'),
] 